// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYt6CmmztxpU-olLG-p2X3GGAoTKF1oWI',
    appId: '1:671553151307:web:6d21e8bdea58b9279c08ce',
    messagingSenderId: '671553151307',
    projectId: 'mynotes-flutter-ren',
    authDomain: 'mynotes-flutter-ren.firebaseapp.com',
    storageBucket: 'mynotes-flutter-ren.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYUNQxuj6macAL15owLNfi7xdxPHoC0H4',
    appId: '1:671553151307:android:b41dea1ae19011559c08ce',
    messagingSenderId: '671553151307',
    projectId: 'mynotes-flutter-ren',
    storageBucket: 'mynotes-flutter-ren.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF2FjjrAlPBYyb_JFOH8Ut9XKx02sZg3k',
    appId: '1:671553151307:ios:7413f4372d0efed19c08ce',
    messagingSenderId: '671553151307',
    projectId: 'mynotes-flutter-ren',
    storageBucket: 'mynotes-flutter-ren.appspot.com',
    iosClientId: '671553151307-6ll8hkilmet5qdgdr3jbrd4put8u1at9.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
